CREATE DATABASE MASCOTAS_FELICES --CREAMOS LA BASE DE DATOS
GO

USE MASCOTAS_FELICES
GO
--******************************************************************************************************
--CREAMOS TODAS LAS TABLAS
CREATE TABLE FUNCIONARIOS (
    ID_FUNCIONARIO INT IDENTITY PRIMARY KEY,
    NOMBRE VARCHAR(20) NOT NULL,
    APELLIDO1 VARCHAR(20) NOT NULL,
    APELLIDO2 VARCHAR(20) NOT NULL,
    CEDULA VARCHAR(20) NOT NULL,
    PUESTO VARCHAR(20) NOT NULL,
    TELEFONO VARCHAR(20) NOT NULL,
    CORREO VARCHAR(50) NOT NULL
);

CREATE TABLE CLIENTES (
    ID_CLIENTE INT IDENTITY PRIMARY KEY,
    NOMBRE VARCHAR(20) NOT NULL,
    APELLIDO1 VARCHAR(20) NOT NULL,
    APELLIDO2 VARCHAR(20) NOT NULL,
    CEDULA VARCHAR(20) NOT NULL,
    TELEFONO VARCHAR(20) NOT NULL,
    CORREO VARCHAR(50) NOT NULL
);

CREATE TABLE PROVEEDORES (
    ID_PROVEEDOR INT IDENTITY PRIMARY KEY,
    NOMBRE VARCHAR(20) NOT NULL,
    TELEFONO VARCHAR(20) NOT NULL,
    CORREO VARCHAR(50) NOT NULL
);

CREATE TABLE PRODUCTOS (
    ID_PRODUCTO INT IDENTITY PRIMARY KEY,
    NOMBRE VARCHAR(20) NOT NULL,
    PRECIO_COMPRA DECIMAL(10, 2) NOT NULL,
    PRECIO_VENTA DECIMAL(10, 2),
    CANTIDAD INT NOT NULL
);

CREATE TABLE BITACORA (
    ID_MOVIMIENTO INT IDENTITY PRIMARY KEY,
    FECHA DATE DEFAULT GETDATE(),
	HORA TIME DEFAULT GETDATE(),
    DESCRIPCION_MOVIMIENTO VARCHAR(150) NOT NULL
);

CREATE TABLE AGENDA (
    ID_AGENDA INT IDENTITY PRIMARY KEY,
    ID_FUNCIONARIO INT NOT NULL,
	FECHA DATE NOT NULL,
    HORA_ENTRADA TIME NOT NULL,
    HORA_SALIDA TIME NOT NULL
);

CREATE TABLE CITAS (
    ID_CITA INT IDENTITY PRIMARY KEY,
    ID_AGENDA INT NOT NULL,
    ID_CLIENTE INT NOT NULL,
    HORA_CITA TIME NOT NULL,
	COSTO DECIMAL(10,2) NOT NULL,
    DESCRIPCION_CITA VARCHAR(100) NOT NULL
);

CREATE TABLE FACTURA_VENTA (
    ID_FACTURA INT IDENTITY PRIMARY KEY,
    ID_CLIENTE INT NOT NULL,
	TOTAL_PAGO DECIMAL(10, 2), 
	FECHA_VENTA DATE DEFAULT GETDATE()
);

CREATE TABLE DETALLE_FACTURA_VENTA (
    ID_DETALLE_FACTURA_VENTA INT IDENTITY PRIMARY KEY,
    ID_FACTURA INT NOT NULL,
    ID_PRODUCTO INT,
	CANTIDAD_PRODUCTO INT,
    ID_CITA INT,
    FECHA_VENTA DATE DEFAULT GETDATE(),
	HORA TIME DEFAULT GETDATE()
);

CREATE TABLE FACTURA_COMPRA (
    ID_FACTURA INT IDENTITY PRIMARY KEY,
    ID_PROVEEDOR INT NOT NULL,
	TOTAL_PAGO DECIMAL(10, 2),
	FECHA_VENTA DATE DEFAULT GETDATE()
);

CREATE TABLE DETALLE_FACTURA_COMPRA (
    ID_DETALLE_FACTURA_COMPRA INT IDENTITY PRIMARY KEY,
    ID_FACTURA INT NOT NULL,
    ID_PRODUCTO INT NOT NULL,
	CANTIDAD_PRODUCTO INT,
    FECHA_VENTA DATE DEFAULT GETDATE(),
	HORA TIME DEFAULT GETDATE()
);

--******************************************************************************************************
--CREAMOS LAS RELACIONES ENTRE LAS TABLAS
ALTER TABLE DETALLE_FACTURA_COMPRA ADD CONSTRAINT FK_DETALLE_FACTURA_COMPRA_FACTURA
    FOREIGN KEY (ID_FACTURA) REFERENCES FACTURA_COMPRA(ID_FACTURA);

ALTER TABLE DETALLE_FACTURA_COMPRA ADD CONSTRAINT FK_DETALLE_FACTURA_COMPRA_PRODUCTOS
    FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTOS(ID_PRODUCTO);

ALTER TABLE AGENDA ADD CONSTRAINT FK_AGENDA_FUNCIONARIO
    FOREIGN KEY (ID_FUNCIONARIO) REFERENCES FUNCIONARIOS(ID_FUNCIONARIO);

ALTER TABLE FACTURA_COMPRA ADD CONSTRAINT FK_FACTURA_PROVEEDORES
    FOREIGN KEY (ID_PROVEEDOR) REFERENCES PROVEEDORES(ID_PROVEEDOR);

ALTER TABLE DETALLE_FACTURA_VENTA ADD CONSTRAINT FK_DETALLE_FACTURA_VENTA_FACTURA
    FOREIGN KEY (ID_FACTURA) REFERENCES FACTURA_VENTA(ID_FACTURA);

ALTER TABLE DETALLE_FACTURA_VENTA ADD CONSTRAINT FK_DETALLE_FACTURA_VENTA_PRODUCTOS
    FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTOS(ID_PRODUCTO);

ALTER TABLE CITAS ADD CONSTRAINT FK_CITAS_AGENDA
    FOREIGN KEY (ID_AGENDA) REFERENCES AGENDA(ID_AGENDA);

ALTER TABLE CITAS ADD CONSTRAINT FK_CITAS_CLIENTES
    FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES(ID_CLIENTE);

ALTER TABLE FACTURA_VENTA ADD CONSTRAINT FK_FACTURA_CLIENTES
    FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES(ID_CLIENTE);
--******************************************************************************************************

